server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: coupon
          uri: http://localhost:8081
          predicates:
            - Path=/coupons/**, 
        - id: point
          uri: http://localhost:8082
          predicates:
            - Path=/points/**, 
        - id: lab
          uri: http://localhost:8083
          predicates:
            - Path=/labs/**, 
        - id: fcpurs
          uri: http://localhost:8084
          predicates:
            - Path=/fcpurs/**, 
        - id: agent
          uri: http://localhost:8085
          predicates:
            - Path=, /loggings/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: coupon
          uri: http://coupon:8080
          predicates:
            - Path=/coupons/**, 
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/points/**, 
        - id: lab
          uri: http://lab:8080
          predicates:
            - Path=/labs/**, 
        - id: fcpurs
          uri: http://fcpurs:8080
          predicates:
            - Path=/fcpurs/**, 
        - id: agent
          uri: http://agent:8080
          predicates:
            - Path=, /loggings/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
